import logging
from typing import Any, Optional

from google.adk.agents.callback_context import CallbackContext
from google.adk.agents.llm_agent import LlmAgent
from google.adk.tools.tool_context import ToolContext
from google.genai import types

from app.agent.prompt.exam_generator_prompt import EXAM_GENERATOR_PROMPT
from app.constants.agent_constants import (
    EXAM_GENERATOR_OUTPUT_FILE_NAME,
    EXAM_GENERATOR_OUTPUT_KEY,
    GEMINI_MODEL
)
from app.util.md import MarkdownUtil

logger = logging.getLogger(__name__)

class ExamGeneratorAgent:

    exam_generator_llm_agent: LlmAgent

    def __init__(self):
        self.exam_generator_llm_agent = LlmAgent(
            model=GEMINI_MODEL,
            name="exam_generator_agent",
            description="Generates exams in markdown based on the provided markdown content.",
            static_instruction=types.Content(
                role="user", parts=[types.Part(text=EXAM_GENERATOR_PROMPT)]
            ),
            instruction=f"""
            EXTRA CONTEXT:
            1. MARKDOWN GENERATED BY READER: {{IMAGE_READER_OUTPUT_KEY}}.
            """,
            output_key=EXAM_GENERATOR_OUTPUT_KEY,
            after_agent_callback = self.__class__.save_markdown_after_agent
        )
        

    def get_agent(self) -> LlmAgent:
        return self.exam_generator_llm_agent

    @staticmethod
    def save_markdown_after_agent(callback_context: CallbackContext) -> Optional[types.Content]:
        generated_markdown = callback_context.state.get(EXAM_GENERATOR_OUTPUT_KEY, "NO MARKDOWN GENERATED")

        if generated_markdown:
            MarkdownUtil.create_markdown_file(text=generated_markdown, file_name=EXAM_GENERATOR_OUTPUT_FILE_NAME)
        
        return None

    
exam_generator_agent = ExamGeneratorAgent()
        